codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: 80%
        threshold: 1%
    patch:
      default:
        target: 80%
        threshold: 1%

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

ignore:
  - "test/**/*"
  - "**/*.g.dart"
  - "**/*.freezed.dart"
  - "lib/generated/**/*"
  - "lib/gen/**/*"

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no 