name: steins_album
description: A privacy-focused photo album management app using CoreML for local inference.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  photo_manager: ^3.6.3
  google_maps_flutter: ^2.3.0
  flutter_staggered_grid_view: ^0.7.0
  intl: ^0.20.1
  path_provider: ^2.1.1
  permission_handler: ^11.3.1
  image_picker: ^1.0.4
  photo_manager_image_provider: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true 